// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PregnAPI.Models;

#nullable disable

namespace PregnAPI.Migrations
{
    [DbContext(typeof(PregnAppContext))]
    [Migration("20240104123835_Ekle")]
    partial class Ekle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PregnAPI.Models.User", b =>
                {
                    b.Property<string>("UserMail")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ReglDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserWeight")
                        .HasColumnType("int");

                    b.HasKey("UserMail");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserMail = "emmrecan.erkus0@gmail.com",
                            ReglDate = new DateTime(2022, 1, 3, 15, 30, 0, 0, DateTimeKind.Unspecified),
                            UserName = "Emrecan",
                            UserPassword = "12345",
                            UserWeight = 97
                        },
                        new
                        {
                            UserMail = "emmrecanreis23@gmail.com",
                            ReglDate = new DateTime(2022, 1, 4, 15, 30, 0, 0, DateTimeKind.Unspecified),
                            UserName = "Elmas",
                            UserPassword = "12345",
                            UserWeight = 47
                        },
                        new
                        {
                            UserMail = "mert.kerim.mert@gmail.com",
                            ReglDate = new DateTime(2022, 4, 3, 15, 30, 0, 0, DateTimeKind.Unspecified),
                            UserName = "FurkanKömürlü",
                            UserPassword = "12345",
                            UserWeight = 67
                        },
                        new
                        {
                            UserMail = "emmr123@gmail.com",
                            ReglDate = new DateTime(2022, 1, 2, 15, 30, 0, 0, DateTimeKind.Unspecified),
                            UserName = "Furkan",
                            UserPassword = "12345",
                            UserWeight = 50
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
