// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PregnAPI.Models;

#nullable disable

namespace PregnAPI.Migrations
{
    [DbContext(typeof(PregnAppContext))]
    [Migration("20240104115918_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PregnAPI.Models.User", b =>
                {
                    b.Property<string>("UserMail")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ReglDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserWeight")
                        .HasColumnType("int");

                    b.HasKey("UserMail");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
